const RAKNET_SetPlayerPos 				= 22;
const RAKNET_SetPlayerPosFindZ 			= 23;
const RAKNET_SetPutVehicle				= 25;
const RAKNET_RemoveVehicle				= 26;
const RAKNET_ShowPlayerDialog			= 77;
const RAKNET_SetPlayerSpectating		= 97;
const RAKNET_SetSpawnPlayer				= 102;
const RAKNET_SetVehiclePos				= 109;
const RAKNET_SetPlayerControllable		= 113;
const RAKNET_ResetPlayerWeapon			= 119;
const RAKNET_GivePlayerWeapon			= 120;
const RAKNET_SetSpawnInfo				= 125;


const RAKNET_PLAYER_SYNC				= 116;
const RAKNET_VEHICLE_SYNC				= 118;
const RAKNET_PASENGER_SYNC				= 115;

