blindtd[0] = TextDrawCreate(0,0," white");
TextDrawFont(blindtd[0],1);
TextDrawLetterSize(blindtd[0],1000,1000);
TextDrawBoxColor(blindtd[0],0x000000AA);
TextDrawUseBox(blindtd[0],1);

blindtd[1] = TextDrawCreate(0,0," white");
TextDrawFont(blindtd[1],1);
TextDrawLetterSize(blindtd[1],1000,1000);
TextDrawBoxColor(blindtd[1],0x000000AA);
TextDrawUseBox(blindtd[1],1);

blindtd[2] = TextDrawCreate(0,0," white");
TextDrawFont(blindtd[2],1);
TextDrawLetterSize(blindtd[2],1000,1000);
TextDrawBoxColor(blindtd[2],0x000000AA);
TextDrawUseBox(blindtd[2],1);

blindtd[3] = TextDrawCreate(0,0," white");
TextDrawFont(blindtd[3],1);
TextDrawLetterSize(blindtd[3],1000,1000);
TextDrawBoxColor(blindtd[3],0x000000AA);
TextDrawUseBox(blindtd[3],1);

blindtd[4] = TextDrawCreate(0,0," white");
TextDrawFont(blindtd[4],1);
TextDrawLetterSize(blindtd[4],1000,1000);
TextDrawBoxColor(blindtd[4],0x000000AA);
TextDrawUseBox(blindtd[4],1);  