// GreenZoneTD[0] = TextDrawCreate(121.500000, 297.055633, "LD_BEAT:chit");
// TextDrawLetterSize(GreenZoneTD[0], 0.000000, 1.357408);
// TextDrawTextSize(GreenZoneTD[0], 42.000000, 0.000000);
// TextDrawAlignment(GreenZoneTD[0], 1);
// TextDrawColor(GreenZoneTD[0], 348223424);
// TextDrawUseBox(GreenZoneTD[0], true);
// TextDrawBoxColor(GreenZoneTD[0], 348223424);
// TextDrawSetShadow(GreenZoneTD[0], 0);
// TextDrawSetOutline(GreenZoneTD[0], 0);
// TextDrawFont(GreenZoneTD[0], 0);

// GreenZoneTD[1] = TextDrawCreate(75.000000, 237.688888, "LD_BEAT:chit");
// TextDrawLetterSize(GreenZoneTD[1], 0.000000, 0.000000);
// TextDrawTextSize(GreenZoneTD[1], 19.500000, 25.511123);
// TextDrawAlignment(GreenZoneTD[1], 1);
// TextDrawColor(GreenZoneTD[1], 348223424);
// TextDrawSetShadow(GreenZoneTD[1], 0);
// TextDrawSetOutline(GreenZoneTD[1], 0);
// TextDrawFont(GreenZoneTD[1], 4);

// GreenZoneTD[2] = TextDrawCreate(-1.000000, 237.444442, "LD_BEAT:chit");
// TextDrawLetterSize(GreenZoneTD[2], 0.000000, 0.000000);
// TextDrawTextSize(GreenZoneTD[2], 17.000000, 26.133344);
// TextDrawAlignment(GreenZoneTD[2], 1);
// TextDrawColor(GreenZoneTD[2], 348223424);
// TextDrawSetShadow(GreenZoneTD[2], 0);
// TextDrawSetOutline(GreenZoneTD[2], 0);
// TextDrawFont(GreenZoneTD[2], 4);

// GreenZoneTD[3] = TextDrawCreate(15.000000, 243.288940, "EEHA OHA");
// TextDrawLetterSize(GreenZoneTD[3], 0.209500, 1.363555);
// TextDrawAlignment(GreenZoneTD[3], 1);
// TextDrawColor(GreenZoneTD[3], -1);
// TextDrawSetShadow(GreenZoneTD[3], 0);
// TextDrawSetOutline(GreenZoneTD[3], 0);
// TextDrawBackgroundColor(GreenZoneTD[3], 51);
// TextDrawFont(GreenZoneTD[3], 2);
// TextDrawSetProportional(GreenZoneTD[3], 1);

GreenZoneTD[0] = TextDrawCreate(625.937072, 195.633331, "usebox");
TextDrawLetterSize(GreenZoneTD[0], 0.000000, 1.461728);
TextDrawTextSize(GreenZoneTD[0], 529.500000, 0.000000);
TextDrawAlignment(GreenZoneTD[0], 1);
TextDrawColor(GreenZoneTD[0], 0);
TextDrawUseBox(GreenZoneTD[0], true);
TextDrawBoxColor(GreenZoneTD[0], 45414143);
TextDrawSetShadow(GreenZoneTD[0], 0);
TextDrawSetOutline(GreenZoneTD[0], 0);
TextDrawFont(GreenZoneTD[0], 0);

GreenZoneTD[1] = TextDrawCreate(520.000000, 188.533325, "LD_BEAT:chit");
TextDrawLetterSize(GreenZoneTD[1], 0.000000, 0.000000);
TextDrawTextSize(GreenZoneTD[1], 25.000000, 27.377788);
TextDrawAlignment(GreenZoneTD[1], 1);
TextDrawColor(GreenZoneTD[1], 45414143);
TextDrawSetShadow(GreenZoneTD[1], 0);
TextDrawSetOutline(GreenZoneTD[1], 0);
TextDrawFont(GreenZoneTD[1], 4);

GreenZoneTD[2] = TextDrawCreate(610.500000, 188.911117, "LD_BEAT:chit");
TextDrawLetterSize(GreenZoneTD[2], 0.000000, 0.000000);
TextDrawTextSize(GreenZoneTD[2], 25.000000, 26.755565);
TextDrawAlignment(GreenZoneTD[2], 1);
TextDrawColor(GreenZoneTD[2], 45414143);
TextDrawSetShadow(GreenZoneTD[2], 0);
TextDrawSetOutline(GreenZoneTD[2], 0);
TextDrawFont(GreenZoneTD[2], 4);

GreenZoneTD[3] = TextDrawCreate(535.000000, 194.133270, "EEHA OHA");
TextDrawLetterSize(GreenZoneTD[3], 0.377999, 1.699555);
TextDrawAlignment(GreenZoneTD[3], 1);
TextDrawColor(GreenZoneTD[3], -1);
TextDrawSetShadow(GreenZoneTD[3], 0);
TextDrawSetOutline(GreenZoneTD[3], 0);
TextDrawBackgroundColor(GreenZoneTD[3], 51);
TextDrawFont(GreenZoneTD[3], 1);
TextDrawSetProportional(GreenZoneTD[3], 1);