#include "../source/server/funcs/uninvite.inc"
#include "../source/server/funcs/kick_all_players.inc"
#include "../source/server/funcs/owner_of_vehicle_by_id.inc"
#include "../source/server/funcs/can_player_get_amount_drugs.inc"
#include "../source/server/funcs/is_able_to_respawne_vehicle.inc"
#include "../source/server/funcs/get_weapon_ammo.inc"

#include "../source/server/funcs/selection_sort.inc"